name: BuilderTools
api: 3.0.0
author: CzechPMDevs
authors: [VixikCZ]
version: 1.2.0-beta2
main: czechpmdevs\buildertools\BuilderTools
website: https://github.com/CzechPMDevs/BuilderTools

permissions:
  bt.cmd:
    default: op
    description: §4Berechtigungen für alle BuilderTools-Befehle
    children:
      bt.cmd.blockinfo:
        description: §4Berechtigungen für //blockinfo
        default: op
      bt.cmd.pos1:
        description: §4Berechtigungen für //pos1
        default: op
      bt.cmd.pos2:
        description: §4Berechtigungen für //pos2
        default: op
      bt.cmd.fill:
        descripion: §4Berechtigungen für //fill
        default: op
      bt.cmd.wand:
        description: §4Berechtigungen für //wand
        default: op
      bt.cmd.commands:
        description: §4Berechtigungen für //commands
        default: op
      bt.cmd.sphere:
        description: §4Berechtigungen für //sphere
        default: op
      bt.cmd.draw:
        description: §4Berechtigungen für //draw
        default: op
      bt.cmd.ip:
        description: §4Berechtigungen für //id
        default: op
      bt.cmd.clearinventory:
        description: §4Berechtigungen für //clearinventory
        default: op
      bt.cmd.naturalize:
        description: §4Berechtigungen für //naturalize
        default: op
      bt.cmd.copy:
        description: §4Berechtigungen für //copy
        default: op
      bt.cmd.paste:
        description: §4Berechtigungen für //paste
        default: op
      bt.cmd.hsphere:
        descripton: §4Berechtigungen für //hsphere
        default: op
      bt.cmd.hcube:
        description: §4Berechtigungen für //hcube
        default: op
      bt.cmd.schematic:
        description: §4Berechtigungen für //schematics
        default: op
      bt.cmd.cylinder:
        description: §4Berechtigungen für //cylinder
        default: op
      bt.cmd.hcylinder:
        description: §4Berechtigungen für //hcylinder
        default: op
      bt.cmd.pyrdamid:
        description: §4Berechtigungen für //pyramid
        default: op
      bt.cmd.hpyrdamid:
        description: §4Berechtigungen für //hpyramid
        default: op
      bt.cmd.stack:
        description: §4Berechtigungen für //stack
        default: op
      bt.cmd.outline:
        description: §Berechtigungen für //outline
        default: op
      bt.cmd.move:
        description: §Berechtigungen für //move
        default: op
      bt.cmd.replace:
        description: §Berechtigungen für //replace
        default: op
      bt.cmd.undo:
        description: §4Berechtigungen für //undo
        default: op
      bt.cmd.redo:
        description: §4Berechtigungen für //redo
        default: op

