name: BuilderTools
api: 3.0.0
author: CzechPMDevs
authors: [VixikCZ]
version: 1.2.0-beta2
main: czechpmdevs\buildertools\BuilderTools
website: https://github.com/CzechPMDevs/BuilderTools

permissions:
  bt.cmd:
    default: op
    description: §4Permissions for all BuilderTools commands
    children:
      bt.cmd.blockinfo:
        description: §4Permissions for //blockinfo
        default: op
      bt.cmd.pos1:
        description: §4Permissions for //pos1
        default: op
      bt.cmd.pos2:
        description: §4Permissions for //pos2
        default: op
      bt.cmd.fill:
        descripion: §4Permissions for //fill
        default: op
      bt.cmd.wand:
        description: §4Permissions for //wand
        default: op
      bt.cmd.commands:
        description: §4Permissions for //commands
        default: op
      bt.cmd.sphere:
        description: §RPermissions for //sphere
        default: op
      bt.cmd.draw:
        description: §4Permissions for //draw
        default: op
      bt.cmd.ip:
        description: §4Permissions for //id
        default: op
      bt.cmd.clearinventory:
        description: §4Permissions for //clearinventory
        default: op
      bt.cmd.naturalize:
        description: §4Permissions for //naturalize
        default: op
      bt.cmd.copy:
        description: §4Permissions for //copy
        default: op
      bt.cmd.paste:
        description: §4Permissions for //paste
        default: op
      bt.cmd.hsphere:
        descripton: §4Permissions for //hsphere
        default: op
      bt.cmd.hcube:
        description: §4Permission for //hcube
        default: op
      bt.cmd.schematic:
        description: §4Permission for //schematics
        default: op
      bt.cmd.cylinder:
        description: §4Permission for //cylinder
        default: op
      bt.cmd.hcylinder:
        description: §4Permission for //hcylinder
        default: op
      bt.cmd.pyrdamid:
        description: §4Permission for //pyramid
        default: op
      bt.cmd.hpyrdamid:
        description: §4Permission for //hpyramid
        default: op
      bt.cmd.stack:
        description: §4Permission for //stack
        default: op
      bt.cmd.outline:
        description: §4Permission for //outline
        default: op
      bt.cmd.move:
        description: §4Permission for //move
        default: op
      bt.cmd.replace:
        description: §4Permission for //replace
        default: op
      bt.cmd.undo:
        description: §4Permission for //undo
        default: op
      bt.cmd.redo:
        description: §4Permission for //redo
        default: op

